[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyjulamoto"
version = "0.1.0"
description = "Python interface to a Julia Kuramoto model"
authors = [{name="Jens Anker Lyngaas", email="jens.lyngaas@gmail.com"}]
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["numpy", "julia"]
